Oprava Issue #81 pres relativni URL
podlomar/python-data pull request #82
Opened 2022-09-15 18:26 UTC by pavelsuk

Teoreticky by to mohlo zafungovat jako fix #81 , ale bude potreba to vyzkouset ve vsech usecasech popsanych v #81 

Prosim o review a pripadny merge (nemam na merge prava)

2022-09-15 18:34 UTC, ZelenyMartin requested changes
Prosim zatim nemergovat. Mel by se na to podivat @podlomar.

2022-09-15 18:40 UTC, pavelsuk commented
Hmm, samo o sobe to zafunguje zase jenom pro jeden z tech usecasu, tj kdyz uz jdu z https://kodim.cz/kurzy/python-data/zaklady-programovani/prvni-programy/prvni-programy a ne kdyz poprve kliknu a dostanu se na https://kodim.cz/kurzy/python-data/zaklady-programovani/prvni-programy

Takze souhlas, nemergovat. Minimalne dokud nebude jasne, jak to spravne referencovat.

Stavajici reseni aspon funguje pro normalni prubeh lekce.

2022-09-18 11:23 UTC, pesikj commented
Podle mě už by to mělo fungovat, co myslíš ty @ZelenyMartin ?

2022-09-18 17:13 UTC, ZelenyMartin approved these changes
CMS se upgradlo a už by to mohlo fungovat.

2022-09-18 17:13 UTC, merged